### ISSUE TITLE
Bug: create transaction edit creditor account status

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [tazama-lf/tazama-demo#12]
Spec: Use case 5: Create transaction: edit account status - extensions 3.a.2. For the creditor, the following information can be updated:
Status (max 4 characters)

**Comment by Sandy-at-Tazama** [comment]
I was able to edit the account status and save it, but clicking on new transaction button set it back to the default/ previous value

**Comment by Sandy-at-Tazama** [comment]
The account status should be defaulted & stored in uppercase

**Comment by KamikaziD** [comment]
Fixed in v1.015

**Comment by Sandy-at-Tazama** [comment]
Tested and fixed in v1.0.15
