### ISSUE TITLE
BUG: udpated account and entity details not stored in the database

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [tazama-lf/tazama-demo#13]
Entity and Account details edited in UI and saved
![image](https://github.com/user-attachments/assets/013103bd-eb49-4045-8257-12ed29146c47)

![image](https://github.com/user-attachments/assets/fdb8d49a-5ade-4c11-9c3e-5c0d2f6e4c2b)

Transaction sent
![image](https://github.com/user-attachments/assets/26a3c990-45c8-4cb6-b21d-fc5291463133)

Default debtor and creditor entity and account details are stored in the database, and not the edited/updated details.  The only edited detail stored in the database is the amount 1.11
![image](https://github.com/user-attachments/assets/d1b70370-dcbb-49d1-99e8-a02618ed8e6d)
![image](https://github.com/user-attachments/assets/6e3d682f-be22-4e05-9339-31848c4f64b4)

**Comment by Sandy-at-Tazama** [comment]
Second transaction for the same entity/account in the DB shows the details are updated

![image](https://github.com/user-attachments/assets/1c2e0098-9d4f-4815-aa67-8e2b97adff73)

![image](https://github.com/user-attachments/assets/16e0c2b7-28f1-4df4-a9a5-934f9e34b70d)

**Comment by KamikaziD** [comment]
Fixed in v1.015

**Comment by Sandy-at-Tazama** [comment]
Tested and confirmed fixed
