### ISSUE TITLE
Demo - bug - runtime error

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [tazama-lf/tazama-demo#2]
After successful or blocked transactions, click on new debitor, click send without clicking on new transactions

This doesn't happen if you click on send the first time when a new debtor is created, only subsequent

![image](https://github.com/user-attachments/assets/cc386892-f98c-44cb-a2ee-ad93778ebf37)

**Comment by KamikaziD** [comment]
Managed to re-create this issue.
Applying error handling fix.

<img width="217" alt="Screenshot 2024-09-05 at 16 01 40" src="https://github.com/user-attachments/assets/b22ab235-7186-45ed-8c15-eaf9112fa2b5">

Fix will be in v1.0.12

**Comment by Sandy-at-Tazama** [comment]
Tested and confirmed fixed
