### ISSUE TITLE
Bug: When cloning, a "new" account is created

### ISSUE THREAD

**Issue by Justus-at-Tazama** [tazama-lf/tazama-demo#4]
## Actual behaviour:
When cloning an entity from debtor to creditor (and vice versa), and then submitting a transaction for the entity, the financial services provider identifier for the account is hard-coded to `fsp001` for debtors and `fsp002` for creditors in the transaction creation process. When the account is created in the database by the API, a new and unique account is created for the account number on the "opposing" side (the side to which the entity was cloned).

## Expected behaviour:
The account information should contain an fspId that is generated when the account is created, and should remain the same when the account is cloned from the debtor to the creditor side (and vice versa).

## Recommendation:
Short term: Default/hard code the financial services provider ID to fsp001 for both the debtor and the creditor side.

**Comment by Sandy-at-Tazama** [comment]
Tested and confirmed fsp001 appears hard-coded
